"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-az_8ou^qve8c21^-245v4o6c1wn((volni_z#v@9&3a^%h)!z8'

# ============== DEBUG AND ALLOWED HOSTS ==============
# Set DEBUG to False in production to prevent sensitive information exposure
DEBUG = False  # Changed to False for production security

# Configure allowed hosts for your domain(s)
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '*']


# ============== APPLICATION DEFINITION ==============

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts.apps.AccountsConfig',  # Custom user model app
    'bookshelf.apps.BookshelfConfig',
    'relationship_app.apps.RelationshipAppConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ============== CUSTOM USER MODEL ==============
# Configure Django to use the custom user model
AUTH_USER_MODEL = 'accounts.CustomUser'

# ============== LOGIN CONFIGURATION ==============
LOGIN_REDIRECT_URL = 'list_books'
LOGIN_URL = 'login'
LOGOUT_REDIRECT_URL = 'login'

# ============== SECURITY SETTINGS - XSS AND CSRF PROTECTION ==============
# Enable XSS filter in browsers to prevent cross-site scripting attacks
SECURE_BROWSER_XSS_FILTER = True

# Prevent browsers from MIME-sniffing response content type
SECURE_CONTENT_TYPE_NOSNIFF = True

# Prevent the site from being framed (clickjacking protection)
X_FRAME_OPTIONS = 'DENY'

# CSRF protection settings
CSRF_COOKIE_SECURE = True  # Only send CSRF cookie over HTTPS
CSRF_COOKIE_HTTPONLY = True  # Prevent JavaScript from accessing CSRF token

# ============== SESSION SECURITY SETTINGS ==============
# Session cookies should only be transmitted over HTTPS
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript from accessing session cookies

# ============== HTTPS AND HSTS SETTINGS ==============
# Redirect all HTTP requests to HTTPS (only in production)
SECURE_SSL_REDIRECT = False  # Set to True in production when HTTPS is available

# HTTP Strict-Transport-Security settings
# Tells browsers to only access the site over HTTPS for a specified period
SECURE_HSTS_SECONDS = 31536000  # One year in seconds
SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # Apply HSTS to all subdomains
SECURE_HSTS_PRELOAD = True  # Allow inclusion in HSTS preload list

# ============== DEFAULT FIELD TYPE ==============
# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
